language: ruby
rvm: 2.5.1
gemfile:
  - Gemfile
sudo: false
before_install:
  - gem install bundler
  - unset RAILS_ENV
  - unset RACK_ENV
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
env:
  - RAILS_VERSION=5.2.1
  - RAILS_VERSION=5.1.6
  - RAILS_VERSION=5.0.7
  - RAILS_VERSION=4.2.10
